name: asset manager
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  portfolio-manager:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Create config directory if it doesn't exist
      run: mkdir -p asset/src/grabber/config

    - name: Write INI config to file
      run: |
        echo -e "${{ secrets.INI_CONFIG }}" > ./asset/src/grabber/config/info.ini
    
    # - name: Print directory structure for debugging
    #   run: ls -R
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: portfolio manager script
      env: 
        CONFIG: ${{ secrets.CONFIG}}
      run: |
        python src/portfolio_manager.py

    - name: Upload screenshot to debug
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: asset/src/grabber/login.png
